### PR TITLE
README: Link to Guile bindings

### PR DESCRIPTION
**Pull request by arunisaac**
Hi,

I have been maintaining guile bindings for xapian for a few years now. Linking to it from the list of language bindings could help visibility.

Thanks,
Arun

### CODE REVIEW

**Comment by ojwb** [comment]
Thanks - will merge when I have a bit more time as there are a few other places to update too.  You might also want to post to the xapian-discuss mailing list to publicise them.

(Don't worry about the CI failures, they're just flaky downloads)

**Comment by arunisaac** [comment]
Hi Olly,

> Thanks - will merge when I have a bit more time as there are a few
> other places to update too.

Thank you very much! And, no hurry.

> You might also want to post to the xapian-discuss mailing list to
> publicise them.

Sure, will do once this PR is merged.

Regards,
Arun

**Comment by ojwb** [comment]
Cherry-picked as a6b5a4f7ac9e68a4dca8217a484cd3272d041811 (and adjusted to preserve alphabetical order of the list).

I also dropped a mention of some much older guile bindings for which the code appears to have unfortunately been completely lost some years ago, and added a link to the website too.

**Comment by arunisaac** [comment]
Thank you! I have written to xapian-discuss as well.

**Pull request closed without merging**
