### PR TITLE
change all i++ to ++i under xapian-letor

### PR DESCRIPTION
**Pull request by Hell0Kitty**
I am a GSoC 2017 Candidate, interested in your Letor Project.

While I am making myself familiar with xapian, I found some improvements can be made:

* change all ++i under Letor part to i++;
I will keep updating if found others things to be improved.

Yu Shining (IRC nickname Ficus)

### CODE REVIEW

**Comment by Hell0Kitty** [comment]
//
   All the changes are made under Letor/test part

**Comment by jaylett** [comment]
Firstly, have you been through the developers guide linked from our GSoC student notes? It talks about good commit practices. You haven't explained why you wanted to make these changes (on counters, in `for` loops, without side effects, won't this be the same but slightly less readable?).

Secondly, you've included three commits you didn't intend to, including one which says it makes a substantive change but then doesn't.

**Comment by ojwb** [comment]
@jaylett It's actually recommended by our style guide:

```
* Prefer "++i;" to "i++;", "i += 1;", or "i = i + 1".  For simple integer
  variables these should generate equivalent (if not identical) code, but if i
  is an iterator object then the pre-increment form can be more efficient in
  some cases with some compilers.  It's simpler and more consistent to always
  use the pre-increment form (unless you make use of the old value which the
  post-increment form returns).  For the same reasons, prefer "--i;" to "i--;",
  "i -= 1;", or "i = i - 1;".
```

So the logic is that `++i` can be more efficient than `i++` for iterators, and that we prefer style rules that don't require considering the type of the variable involved to know what to write.

Modern compilers can probably optimise away the extra overhead from `i++` if the `operator++(int)` method is inlined and written suitably - as HACKING says elsewhere:

```
The postfix operator++ for iterators should be implemented inline in terms
  of the prefix form as described by Joe Buck on the gcc mailing list
~ - excerpt from http://article.gmane.org/gmane.comp.gcc.devel/50201 ::
  
          class some_iterator {
          public:
              // ...
              some_iterator& operator++();
  
              some_iterator operator++(int) {
                  some_iterator tmp = *this;
                  operator++();
                  return tmp;
              }
          };
  
      The compiler is allowed to assume that the copy constructor only does
      a copy, and to optimize away unneeded copy operations.  The result
      in this case should be that, for some_iterator above, using the
      postfix operator without using the result should give code equivalent
      to using the prefix operator.
  
      Now, for [GCC 3.4], you'll find that the dead uses of tmp are only
      completely optimized away if tmp has only one data member that can fit in a
      register.  [GCC 4.0 will do] better, and you should find that this style
      comes very close to eliminating any penalty from "incorrect" use of the
      postfix form.
  
  Xapian's PostingIterator, TermIterator, PositionIterator, and ValueIterator all
  have only one data member which fits in a register.
```

Our minimum GCC requirement is 4.7 for 1.4.x, and 4.8 for git master.

Also the most common place where you need to increment iterators is in a loop over a container, and with C++11 `for (iterator i = c.begin(); i != c.end(); ++i) { do_something(*i); }` loop is better written as `for (auto&& i : c) { do_something(i); }` anyway.

So possibly things have moved on and this should be reconsidered, though there's the issue of third-party iterators which don't implement `operator++(int)` as an inline wrapper.

It's certainly something that people often "get wrong" in submitted patches, and I can understand why as `i++` is a common idiom for "increment i" at least in C code where the side-effect or returning the old value can clearly be trivially optimised away if it's unused.

But as things stand, the final commit seems useful as it fixes deviations from our style guide.  The other 3 commits should be removed (`git rebase -i` and just delete them from the list, then `git push --force` to update the branch for this PR).

**Comment by ojwb** [comment]
The final commit actually introduces a new deviation from the style guide as one of the changed lines is now indented with 8 spaces instead of a tab, which is why the CI reports a failure:

https://travis-ci.org/xapian/xapian/jobs/213023127

**Comment by jaylett** [comment]
@ojwb I'm not opposed to the change, but it needs some justification in the commit message IMHO. I understand why it's important for general iterators, but I don't really think of integers (which two of the changes are) as iterators, hence having a justifying commit message would I think be helpful.

Certainly:

> all i++ changed to ++i under xapian-letor

isn't a great message because it just repeats what the change is (with the marginal detail that we're changing all of them). "Prefer postfix increment for iterators" might be a better subject, for instance, followed by some explanation noting the style guide.

**Comment by ojwb** [comment]
> @ojwb I'm not opposed to the change, but it needs some justification in the
> commit message IMHO.

Indeed, I wasn't intended to disagree with that.  I was just filling
in the background.

> all i++ changed to ++i under xapian-letor
>
> isn't a great message because it just repeats what the change is (with the
> marginal detail that we're changing all of them). "Prefer postfix increment
> for iterators" might be a better subject, for instance, followed by some
> explanation noting the style guide.

Yes, except that should be "Prefer prefix"!

**Comment by jaylett** [comment]
D'oh! Prefer prefix, indeed :)

**Comment by Hell0Kitty** [comment]
Thank you very much for your reviews!
Can I just open a new pull request with a proper commit message, and replace the white space with tab?

**Comment by ojwb** [comment]
Can I just open a new pull request with a proper commit message, and
replace the white space with tab?

Much better to fix up the branch locally and force push it to update the
existing PR.

**Pull request closed without merging**
