### PR TITLE
outlook

### PR DESCRIPTION
**Pull request by uhuntu**
When I was trying to translate some Chinese letters, seems with encoding, it will come out wrong characters.

### CODE REVIEW

**Comment by ojwb** [comment]
Removing escaping here is not the right thing to do - it will result in text emails containing characters such as `<`, `>` and `&` getting mangled.

What problem are you actually trying to solve with this change?

**Comment by uhuntu** [comment]
When I was trying to translate some Chinese letters, seems with encoding, it will come out wrong characters.

**Comment by ojwb** [comment]
I tried with some sample .msg files and I think I can reproduce:

```
./outlookmsg2html tst_unicode.msg
Use of uninitialized value in string eq at /usr/share/perl5/Email/Outlook/Message/AddressInfo.pm line 76.
<head>
<title>Testcase</title>
<meta name="author" content="">
<meta name="created" content="2019-10-21T11:29:02">
</head>
<pre>-/-
Char-&Atilde;&yen;-Char
-/-
Char-&Atilde;&#133;-Char
-/-
Char-&Atilde;&cedil;-Char
-/-
Char-&Atilde;&#152;-Char
-/-
Char-&Atilde;&brvbar;-Char
-/-
Char-&Atilde;&#134;-Char
 
</pre>
```

Looks like the escaping is treating the string as ISO-8859-1 rather than UTF-8.  I think the appropriate fix is something along the lines of this, which solves the problem for my example at least:

```
diff --git a/xapian-applications/omega/outlookmsg2html.in b/xapian-applications/omega/outlookmsg2html.in
index 86c1a430b648..d96f318b192c 100644
--- a/xapian-applications/omega/outlookmsg2html.in
+++ b/xapian-applications/omega/outlookmsg2html.in
@@ -24,6 +24,7 @@
 # IN THE SOFTWARE.
 
 use strict;
+use Encode 'decode';
 eval {
     require Email::Outlook::Message;
     require HTML::Entities;
@@ -62,7 +63,7 @@ handle_mimepart($mime);
 
 sub do_header {
     my ($msg, $header) = @_;
-    my $s = $msg->header_str($header);
+    my $s = decode('utf-8', $msg->header_str($header));
     return HTML::Entities::encode_entities($s);
 }
 
@@ -85,7 +86,8 @@ sub handle_mimepart {
 	}
     } elsif ($type eq 'text') {
 	if ($sub eq 'plain') {
-	    print "<pre>", HTML::Entities::encode_entities($e->body), "</pre>\n";
+	    my $body = decode('utf-8', $e->body);
+	    print "<pre>", HTML::Entities::encode_entities($body), "</pre>\n";
 	    return 1;
 	} elsif ($sub eq 'html') {
 	    my $m = $e->body;
```

Does that solve it for you?

**Comment by uhuntu** [comment]
Unfortunately no.

**Comment by ojwb** [comment]
@uhuntu Can you provide a testcase?

**Comment by uhuntu** [comment]
@ojwb Hi Olly, I leave you a message by your email, there is a test case I can give.

**Comment by ojwb** [comment]
Thanks - changing to `body_str` seems to fix your testcase.

There are 4 warning messages still:

```
Value for 'Subject' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
Value for 'From' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
Value for 'To' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
Value for 'Cc' header with wide characters at /usr/share/perl5/Email/Outlook/Message.pm line 320.
```

That looks like a bug in Email::Outlook - I think it should call `header_str_set` rather than `header_set` there, or maybe check whether the string to set it Unicode or raw bytes and call different methods depending.  I'll see if I can submit a patch for that upstream, but it doesn't seem to cause problems with the output of our script at least.

**Comment by uhuntu** [comment]
@ojwb Hello Olly, sorry I can not agree to close this issue, I pulled the latest master with your commit, but seems the issue did not gone. In my case, I just use `/usr/local/lib/xapian-omega/bin/outlookmsg2html` that living in my machine to determine the issue.

For example, that email I sent you `outlookmsg2html 'Redmin - RFQ  Catalog少 B8 這個欄位 .msg'`, I just check the message output, if just apply your patch, seems issue still exist.

**Comment by ojwb** [comment]
With the commit before the fix (0029277c23052eccc42d8581bc3a13c8c1101fe7) I get:

```
<head>
<title>&lt;Redmin - RFQ / Catalog&#x5C11; B8 &#x9019;&#x500B;&#x6B04;&#x4F4D;&gt; </title>
<meta name="author" content="&quot;Judy.Lin &#x6797;&#x6DD1;&#x8C9E;&quot; &lt;Judy.Lin@tes-tec.com&gt;">
<meta name="created" content="2023-04-10T02:40:52">
</head>
<pre>Dear Hunt:

 

Redmin -  RFQ / Catalog : &aring;&deg;&#145; B8 &eacute;&#128;&#153;&aring;&#128;&#139;&aelig;&not;&#132;&auml;&frac12;&#141;, &egrave;&laquo;&#139;&aelig;&#130;&uml;&aring;&sup1;&laquo;&aring;&iquest;&#153;&aring;&cent;&#158;&aring;&#138;&nbsp;, &egrave;&not;&#157;&egrave;&not;&#157;.

 



 



 

 

 

Best regards!

Judy.Lin 

02-77228751 (&aring;&deg;&#136;&ccedil;&middot;&#154;)

</pre>
```

With the fix (6dc668a1c909daaa3edc9543369c6aabe06bd836) I get:

```
<head>
<title>&lt;Redmin - RFQ / Catalog&#x5C11; B8 &#x9019;&#x500B;&#x6B04;&#x4F4D;&gt; </title>
<meta name="author" content="&quot;Judy.Lin &#x6797;&#x6DD1;&#x8C9E;&quot; &lt;Judy.Lin@tes-tec.com&gt;">
<meta name="created" content="2023-04-10T02:40:52">
</head>
<pre>Dear Hunt:

 

Redmin -  RFQ / Catalog : &#x5C11; B8 &#x9019;&#x500B;&#x6B04;&#x4F4D;, &#x8ACB;&#x60A8;&#x5E6B;&#x5FD9;&#x589E;&#x52A0;, &#x8B1D;&#x8B1D;.

 



 



 

 

 

Best regards!

Judy.Lin 

02-77228751 (&#x5C08;&#x7DDA;)

</pre>
```

I'm not fluent in Chinese, but decoding the HTML from the second one and pasting it into google translate strongly suggested it has decoded correctly.

If the second output is not correct, you'll need to pin-point exactly which part is still wrong.

If you're getting different output with the fixed `outlookmsg2html` to me then I'd suggest trying with the latest Email::Outlook Perl module - e.g. 0.920 and 0.921 both include Unicode-related fixes.  I'm using 0.921 (as packaged for Debian unstable).

**Comment by uhuntu** [comment]
Thanks for explain, it works as expect.

**Pull request closed without merging**
