### PR TITLE
letor: Enable Travis and remove xapian-letor from default bootstrap

### PR DESCRIPTION
**Pull request by ayshtmr**
This PR does the following:

1. Delete `xapian-letor/.nobootstrap`
2. Remove `xapian-letor` from bootstrap defaults
3. Create `letor-bootstrap` in the top-level directory
4. Update `xapian-letor/README` for new build and install instructions
5. Update `.travis.yml` to add xapian-letor build scripts, and add `libsvm` to package dependency.

### CODE REVIEW

**Comment by ojwb** [comment]
What's the purpose of adding `letor-bootstrap`, etc?

You're on a branch - why not just modify `bootstrap` itself to do what you want?

**Comment by ayshtmr** [comment]
I had a discussion with @jaylett on using Travis to test future `xapian-letor` PRs. Since `xapian-letor` has extra dependency on `libsvm`, without making major changes to `bootstrap`, I created `letor-bootstrap` separately and updated `.travis.yml` accordingly.

Am I doing something wrong?

**Comment by jaylett** [comment]
Sorry, I could have been more clear. Just change the `.travis.yml` invocation of `./bootstrap` to include the subprojects to build explicitly:

```
before_script:
  - ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
  - ./configure
```

Because we've removed `xapian-letor` from the defaults, people won't accidentally build it (and won't get annoyed if they don't have `libsvm` installed), but it's easy for people to build with LTR, including the Travis test runs, because the repo won't have a `.nobootstrap` which needs clearing out first.

**Comment by ayshtmr** [comment]
I see. Thanks for the clarification. Closing this PR and pushing travis commits with `bootstrap` and `.travis.yml` changes to PR#116: Remove RankList.

**Pull request closed without merging**
