### PR TITLE
GSoC 2014 Pull Request from VcamX

### PR DESCRIPTION
**Pull request by VcamX**

### CODE REVIEW

**Comment by ojwb** [comment]
I seem to have managed to close all open PRs 28 days ago, which wasn't intended - reopening.

**Comment by ojwb** [comment]
@AyushP123 You merged a lot of this work last year - is there anything left here still to do?

**Comment by AyushP123** [comment]
I went through the commits, everything in this PR has been merged either directly or after some modifications. There is nothing left here that is pending.

**Comment by ojwb** [comment]
Thanks for checking, and thanks to you both for all your work on this.

Closing now.

**Pull request closed without merging**
